In [1]:
# Imports
from bokeh.plotting import figure, show
import pandas as pd
from bokeh.models import ColumnDataSource
from bokeh.models import LassoSelectTool, HoverTool
from bokeh.transform import linear_cmap

In [2]:
penguin_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"

In [3]:
# Load dataset to pandas dataframe
penguin_data = pd.read_csv(penguin_url)

In [4]:
penguin_data

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [6]:
# Scale dataset
scaling_factor = 40
penguin_data["body_mass_g_scaled"] = penguin_data["body_mass_g"] / penguin_data["body_mass_g"].max() * scaling_factor

In [7]:
penguin_data

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_g_scaled
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,23.809524
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,24.126984
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,20.634921
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,21.904762
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE,30.793651
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE,36.507937
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE,33.015873
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE,34.285714

In [8]:
# Convert dataframe to Bokeh's data model
penguin_cds = ColumnDataSource(penguin_data)

In [9]:
# Create figure object with title
p_hover = figure(title="Figure including hover tool")

In [10]:
# Create hover tool object and pass titles and column names in the datasets
hover_tool = HoverTool(tooltips=[("Bill length [mm]", "@bill_length_mm"),
                                 ("Bill depth [mm]", "@bill_depth_mm"),
                                 ("Body mass [g]", "@body_mass_g"),
                                 ("Species", "@species")])

In [11]:
# Add the hover tool object to the figure object
p_hover.add_tools(hover_tool)

In [12]:
# Plot circles on the figure with scalled data as size of the circle
p_hover.circle(source=penguin_cds, x="bill_length_mm", y="bill_depth_mm",
              size="body_mass_g_scaled", alpha=0.5)

GlyphRenderer(id='p1059', ...)

In [13]:
show(p_hover)

Opening in existing browser session.